version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "03:00"
      timezone: "Europe/London"
    open-pull-requests-limit: 10
    versioning-strategy: increase
    commit-message:
      prefix: "chore"
      include: "scope"

    # These packages change constantly, and we really don't care
    ignore:
      - dependency-name: "caniuse-lite"
        update-types:
          - "version-update:semver-patch"
      - dependency-name: "electron-to-chromium"
        update-types:
          - "version-update:semver-patch"
      - dependency-name: "browserslist"
        update-types:
          - "version-update:semver-patch"

    groups:
      # Group together packages that change frequently due to
      # tracking browser versions, and update only when significant.
      browserversions:
        patterns:
          - "browserslist"
          - "caniuse-lite"
          - "electron-to-chromium"

      eslint:
        patterns:
          - "@eslint/*"
          - "eslint*"
          - "typescript-eslint"
          - "@typescript-eslint/*"
