version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "03:00"
      timezone: "Europe/London"
    open-pull-requests-limit: 10
    versioning-strategy: increase
    commit-message:
      prefix: "chore"
      include: "scope"

    allow:
      - dependency-type: "all"

    groups:
      # Group together packages that change frequently due to
      # tracking browser versions, and update only when significant.
      browserversions:
        patterns:
          - "browserslist"
          - "caniuse-lite"
          - "electron-to-chromium"
        update-types:
          - "major"
          - "minor"
          
      eslint:
        patterns:
          - "@eslint/*"
          - "eslint*"
          - "typescript-eslint"
        update-types:
          - "major"
          - "minor"
