name: Pull Request CI
on:
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x, 22.x, 24.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: "https://registry.npmjs.org"
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - name: Build package
        run: npm run build
      - name: Run tests
        run: npm test

  # Collect the above matrix together into a single check that PRs can be blocked on
  ci-success:
    runs-on: ubuntu-latest
    needs: [build-and-test]
    if: always()
    steps:
      - name: Check build and test results
        run: |
          if [ "${{ needs.build-and-test.result }}" != "success" ]; then
            echo "Build and test failed"
            exit 1
          fi
          echo "All checks passed"
